version: "3"
services:
  web:
    build:
      context: PatientPortal.Web
    ports:
      - 8081:8081
    environment:
      - Api:Host=api
    links:
      - api
    depends_on:
      - api
  api:
    build:
      context: PatientPortal.Api
    ports:
      - 5001:5001
    environment:
      - Database:Host=db
    links:
      - db
    depends_on:
      - db
  db:
    build:
      context: PatientPortal.Database
    ports:
      - 1433:1433
  tests:
    build:
      context: .
      dockerfile: PatientPortal.Api.Tests/Dockerfile
    environment:
      - Database:Host=db
    links:
      - db
