version: "3"
services:
  web:
    build:
      context: PatientPortal.Web
    ports:
      - 8080:8080
    environment:
      - Api:Host=api
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - api
    depends_on:
      - api
  api:
    build:
      context: PatientPortal.Api
    ports:
      - 5001:5001
    environment:
      - Database:Host=db
    links:
      - db
    depends_on:
      - db
  db:
    build:
      context: PatientPortal.Database
    ports:
      - 1433:1433
