version: "3"
services:
  web:
    build:
      context: PatientPortal.Web
    ports:
      - 8080:8080
    links:
      - api
    depends_on:
      - api
  api:
    build:
      context: PatientPortal.Api
    ports:
      - 5001:5001
    links:
      - db
    depends_on:
      - db
  db:
    build:
      context: PatientPortal.Database
    ports:
      - 1433:1433
